FABIC: musl: #if 0 ... around definition of struct sysinfo {} #endif
Breaks LLVM/Clang build with :

    In file included from /home/fabi/dev/llvm2/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:63:
    In file included from /home/fabi/dev/llvm2/local/include/linux/sysctl.h:25:
    In file included from /home/fabi/dev/llvm2/local/include/linux/kernel.h:4:
    /home/fabi/dev/llvm2/local/include/linux/sysinfo.h:7:8: error: redefinition of 'sysinfo'
    struct sysinfo {
	   ^
    /home/fabi/dev/llvm2/local/include/sys/sysinfo.h:10:8: note: previous definition is here
    struct sysinfo {
	   ^

NOTE: Installed the Linux headers under local/include/ along the way.